services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4004:4004
    environment:
      - DB_HOST=db
      - DB_PASS=${DB_PASS}
  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - 'db_data:/var/lib/postgresql/data:rw'
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
volumes:
  db_data:
